---
name: idr0083-lamers-sarscov2/experimentA
version: 1

defaults:
  include: no
  type: string
  split: ;
  includeclient: yes
  visible: yes
  omitempty: yes

columns:

  - name: Experimental Condition [Infectious Agent]
    clientname: Infectious Agent
    include: yes

  - name: Assay Name
    clientname: Assay Name
    include: yes

  - name: Source Name
    clientname: Source Name
    include: yes

  - name: Comment [Image File]
    clientname: Comment
    include: yes


  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism 1]
          clientname: Organism
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism 2]
          clientname: Organism
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/cell_line
      columns:
      - name: Characteristics [Cell Line]
        clientname: Cell Line
        include: yes

advanced:
  ignore_missing_primary_key: yes
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
    - namespace: openmicroscopy.org/mapr/cell_line
      keys:
      - Cell Line
